package com.leithcarsreports.presentation.reports

object AlmntakaAlhora {
    val SalesMan1Name = ReportsViewModel.CellIndex(row = 2, column = 16)
    val SalesMan1Value = ReportsViewModel.CellIndex(row = 2, column = 2)
    val SalesMan2Name = ReportsViewModel.CellIndex(row = 3, column = 16)
    val SalesMan2Value = ReportsViewModel.CellIndex(row = 3, column = 2)
    val SalesMan3Name = ReportsViewModel.CellIndex(row = 4, column = 16)
    val SalesMan3Value = ReportsViewModel.CellIndex(row = 4, column = 2)
    val SalesMan4Name = ReportsViewModel.CellIndex(row = 5, column = 16)
    val SalesMan4Value = ReportsViewModel.CellIndex(row = 5, column = 2)
    val SalesMan5Name = ReportsViewModel.CellIndex(row = 6, column = 16)
    val SalesMan5Value = ReportsViewModel.CellIndex(row = 6, column = 2)
    val SalesMan6Name = ReportsViewModel.CellIndex(row = 7, column = 16)
    val SalesMan6Value = ReportsViewModel.CellIndex(row = 7, column = 2)
    val SalesMan7Name = ReportsViewModel.CellIndex(row = 8, column = 16)
    val SalesMan7Value = ReportsViewModel.CellIndex(row = 8, column = 2)

    val DongFengName = ReportsViewModel.CellIndex(row = 1, column = 15)
    val DongFengValue = ReportsViewModel.CellIndex(row = 9, column = 15)
    val BydName = ReportsViewModel.CellIndex(row = 1, column = 14)
    val BydValue = ReportsViewModel.CellIndex(row = 9, column = 14)
    val VwID3_4_6Name = ReportsViewModel.CellIndex(row = 1, column = 13)
    val VwID3_4_6Value = ReportsViewModel.CellIndex(row = 9, column = 13)
    val Honda_E_Ns1Name = ReportsViewModel.CellIndex(row = 1, column = 12)
    val Honda_E_Ns1Value = ReportsViewModel.CellIndex(row = 9, column = 12)
    val UsedName = ReportsViewModel.CellIndex(row = 1, column = 11)
    val UsedValue = ReportsViewModel.CellIndex(row = 9, column = 11)
    val WulingName = ReportsViewModel.CellIndex(row = 1, column = 10)
    val WulingValue = ReportsViewModel.CellIndex(row = 9, column = 10)
    val JmevName = ReportsViewModel.CellIndex(row = 1, column = 9)
    val JmevValue = ReportsViewModel.CellIndex(row = 9, column = 9)
    val JacName = ReportsViewModel.CellIndex(row = 1, column = 8)
    val JacValue = ReportsViewModel.CellIndex(row = 9, column = 8)
    val MgName = ReportsViewModel.CellIndex(row = 1, column = 7)
    val MgValue = ReportsViewModel.CellIndex(row = 9, column = 7)


}

object KhaldaMulitBrand {
    val SalesMan1Name = ReportsViewModel.CellIndex(row = 12, column = 16)
    val SalesMan1Value = ReportsViewModel.CellIndex(row = 12, column = 2)
    val SalesMan2Name = ReportsViewModel.CellIndex(row = 13, column = 16)
    val SalesMan2Value = ReportsViewModel.CellIndex(row = 13, column = 2)
    val SalesMan3Name = ReportsViewModel.CellIndex(row = 14, column = 16)
    val SalesMan3Value = ReportsViewModel.CellIndex(row = 14, column = 2)
    val SalesMan4Name = ReportsViewModel.CellIndex(row = 15, column = 16)
    val SalesMan4Value = ReportsViewModel.CellIndex(row = 15, column = 2)
    val SalesMan5Name = ReportsViewModel.CellIndex(row = 16, column = 16)
    val SalesMan5Value = ReportsViewModel.CellIndex(row = 16, column = 2)

    val DongFengName = ReportsViewModel.CellIndex(row = 11, column = 15)
    val DongFengValue = ReportsViewModel.CellIndex(row = 17, column = 15)
    val BydName = ReportsViewModel.CellIndex(row = 11, column = 14)
    val BydValue = ReportsViewModel.CellIndex(row = 17, column = 14)
    val VwID3_4_6Name = ReportsViewModel.CellIndex(row = 11, column = 13)
    val VwID3_4_6Value = ReportsViewModel.CellIndex(row = 17, column = 13)
    val Honda_E_Ns1Name = ReportsViewModel.CellIndex(row = 11, column = 12)
    val Honda_E_Ns1Value = ReportsViewModel.CellIndex(row = 17, column = 12)
    val UsedName = ReportsViewModel.CellIndex(row = 11, column = 11)
    val UsedValue = ReportsViewModel.CellIndex(row = 17, column = 11)
    val WulingName = ReportsViewModel.CellIndex(row = 11, column = 10)
    val WulingValue = ReportsViewModel.CellIndex(row = 17, column = 10)
    val JmevName = ReportsViewModel.CellIndex(row = 11, column = 9)
    val JmevValue = ReportsViewModel.CellIndex(row = 17, column = 9)
    val JacName = ReportsViewModel.CellIndex(row = 11, column = 8)
    val JacValue = ReportsViewModel.CellIndex(row = 17, column = 8)
    val MgName = ReportsViewModel.CellIndex(row = 11, column = 7)
    val MgValue = ReportsViewModel.CellIndex(row = 17, column = 7)
}

object KkaldaDongFeng {
    val SalesMan1Name = ReportsViewModel.CellIndex(row = 20, column = 16)
    val SalesMan1Value = ReportsViewModel.CellIndex(row = 20, column = 2)
    val SalesMan2Name = ReportsViewModel.CellIndex(row = 21, column = 16)
    val SalesMan2Value = ReportsViewModel.CellIndex(row = 21, column = 2)
    val SalesMan3Name = ReportsViewModel.CellIndex(row = 22, column = 16)
    val SalesMan3Value = ReportsViewModel.CellIndex(row = 22, column = 2)
    val SalesMan4Name = ReportsViewModel.CellIndex(row = 23, column = 16)
    val SalesMan4Value = ReportsViewModel.CellIndex(row = 23, column = 2)
    val SalesMan5Name = ReportsViewModel.CellIndex(row = 24, column = 16)
    val SalesMan5Value = ReportsViewModel.CellIndex(row = 24, column = 2)
    val SalesMan6Name = ReportsViewModel.CellIndex(row = 25, column = 16)
    val SalesMan6Value = ReportsViewModel.CellIndex(row = 25, column = 2)

    val BydName = ReportsViewModel.CellIndex(row = 19, column = 3)
    val BydValue = ReportsViewModel.CellIndex(row = 26, column = 3)
    val HugeName = ReportsViewModel.CellIndex(row = 19, column = 15)
    val HugeValue = ReportsViewModel.CellIndex(row = 26, column = 4)
    val Rich_6Name = ReportsViewModel.CellIndex(row = 19, column = 13)
    val Rich_6Value = ReportsViewModel.CellIndex(row = 26, column = 5)
    val MnvName = ReportsViewModel.CellIndex(row = 19, column = 12)
    val MnvValue = ReportsViewModel.CellIndex(row = 26, column = 6)
    val M5Name = ReportsViewModel.CellIndex(row = 19, column = 11)
    val M5Value = ReportsViewModel.CellIndex(row = 26, column = 7)
    val v_e4Name = ReportsViewModel.CellIndex(row = 19, column = 10)
    val v_e4Value = ReportsViewModel.CellIndex(row = 26, column = 8)
    val FridayName = ReportsViewModel.CellIndex(row = 19, column = 9)
    val FridayValue = ReportsViewModel.CellIndex(row = 26, column = 9)
    val S60Name = ReportsViewModel.CellIndex(row = 19, column = 8)
    val S60Value = ReportsViewModel.CellIndex(row = 26, column = 10)
    val A30Name = ReportsViewModel.CellIndex(row = 19, column = 7)
    val A30Value = ReportsViewModel.CellIndex(row = 26, column = 11)
    val D60Name = ReportsViewModel.CellIndex(row = 19, column = 8)
    val D60Value = ReportsViewModel.CellIndex(row = 26, column = 12)
    val E70Name = ReportsViewModel.CellIndex(row = 19, column = 7)
    val E70Value = ReportsViewModel.CellIndex(row = 26, column = 13)
    val Ex1Name = ReportsViewModel.CellIndex(row = 19, column = 8)
    val Ex1Value = ReportsViewModel.CellIndex(row = 26, column = 14)
    val A60maxName = ReportsViewModel.CellIndex(row = 19, column = 7)
    val A60maxValue = ReportsViewModel.CellIndex(row = 26, column = 15)
}

object Arbad {
    val SalesMan1Name = ReportsViewModel.CellIndex(row = 30, column = 16)
    val SalesMan1Value = ReportsViewModel.CellIndex(row = 30, column = 2)
    val SalesMan2Name = ReportsViewModel.CellIndex(row = 31, column = 16)
    val SalesMan2Value = ReportsViewModel.CellIndex(row = 31, column = 2)
    val SalesMan3Name = ReportsViewModel.CellIndex(row = 32, column = 16)
    val SalesMan3Value = ReportsViewModel.CellIndex(row = 32, column = 2)
    val SalesMan4Name = ReportsViewModel.CellIndex(row = 33, column = 16)
    val SalesMan4Value = ReportsViewModel.CellIndex(row = 33, column = 2)
    val SalesMan5Name = ReportsViewModel.CellIndex(row = 34, column = 16)
    val SalesMan5Value = ReportsViewModel.CellIndex(row = 34, column = 2)
    val SalesMan6Name = ReportsViewModel.CellIndex(row = 35, column = 16)
    val SalesMan6Value = ReportsViewModel.CellIndex(row = 35, column = 2)

    val DongFengName = ReportsViewModel.CellIndex(row = 29, column = 15)
    val DongFengValue = ReportsViewModel.CellIndex(row = 36, column = 15)
    val BydName = ReportsViewModel.CellIndex(row = 29, column = 14)
    val BydValue = ReportsViewModel.CellIndex(row = 36, column = 14)
    val VwID3_4_6Name = ReportsViewModel.CellIndex(row = 29, column = 13)
    val VwID3_4_6Value = ReportsViewModel.CellIndex(row = 36, column = 13)
    val Honda_E_Ns1Name = ReportsViewModel.CellIndex(row = 29, column = 12)
    val Honda_E_Ns1Value = ReportsViewModel.CellIndex(row = 36, column = 12)
    val UsedName = ReportsViewModel.CellIndex(row = 29, column = 11)
    val UsedValue = ReportsViewModel.CellIndex(row = 36, column = 11)
    val WulingName = ReportsViewModel.CellIndex(row = 29, column = 10)
    val WulingValue = ReportsViewModel.CellIndex(row = 36, column = 10)
    val JmevName = ReportsViewModel.CellIndex(row = 29, column = 9)
    val JmevValue = ReportsViewModel.CellIndex(row = 36, column = 9)
    val JacName = ReportsViewModel.CellIndex(row = 29, column = 8)
    val JacValue = ReportsViewModel.CellIndex(row = 36, column = 8)
    val MgName = ReportsViewModel.CellIndex(row = 29, column = 7)
    val MgValue = ReportsViewModel.CellIndex(row = 36, column = 7)
}

object Fleet {
    val SalesMan1Name = ReportsViewModel.CellIndex(row = 39, column = 16)
    val SalesMan1Value = ReportsViewModel.CellIndex(row = 39, column = 15)

    val DongFengName = ReportsViewModel.CellIndex(row = 38, column = 15)
    val DongFengValue = ReportsViewModel.CellIndex(row = 39, column = 15)
    val BydName = ReportsViewModel.CellIndex(row = 38, column = 14)
    val BydValue = ReportsViewModel.CellIndex(row = 39, column = 14)
    val VwID3_4_6Name = ReportsViewModel.CellIndex(row = 38, column = 13)
    val VwID3_4_6Value = ReportsViewModel.CellIndex(row = 39, column = 13)
    val Honda_E_Ns1Name = ReportsViewModel.CellIndex(row = 38, column = 12)
    val Honda_E_Ns1Value = ReportsViewModel.CellIndex(row = 39, column = 12)
    val UsedName = ReportsViewModel.CellIndex(row = 38, column = 11)
    val UsedValue = ReportsViewModel.CellIndex(row = 39, column = 11)
    val WulingName = ReportsViewModel.CellIndex(row = 38, column = 10)
    val WulingValue = ReportsViewModel.CellIndex(row = 39, column = 10)
    val JmevName = ReportsViewModel.CellIndex(row = 38, column = 9)
    val JmevValue = ReportsViewModel.CellIndex(row = 39, column = 9)
    val JacName = ReportsViewModel.CellIndex(row = 38, column = 8)
    val JacValue = ReportsViewModel.CellIndex(row = 39, column = 8)
    val MgName = ReportsViewModel.CellIndex(row = 38, column = 7)
    val MgValue = ReportsViewModel.CellIndex(row = 39, column = 7)
}

object TotalCarsSells{
    val DongFengName = ReportsViewModel.CellIndex(row = 40, column = 15)
    val DongFengValue = ReportsViewModel.CellIndex(row = 41, column = 15)
    val BydName = ReportsViewModel.CellIndex(row = 40, column = 14)
    val BydValue = ReportsViewModel.CellIndex(row = 41, column = 14)
    val VwID3_4_6Name = ReportsViewModel.CellIndex(row = 40, column = 13)
    val VwID3_4_6Value = ReportsViewModel.CellIndex(row = 41, column = 13)
    val Honda_E_Ns1Name = ReportsViewModel.CellIndex(row = 40, column = 12)
    val Honda_E_Ns1Value = ReportsViewModel.CellIndex(row = 41, column = 12)
    val UsedName = ReportsViewModel.CellIndex(row = 40, column = 11)
    val UsedValue = ReportsViewModel.CellIndex(row = 41, column = 11)
    val WulingName = ReportsViewModel.CellIndex(row = 40, column = 10)
    val WulingValue = ReportsViewModel.CellIndex(row = 41, column = 10)
    val JmevName = ReportsViewModel.CellIndex(row = 40, column = 9)
    val JmevValue = ReportsViewModel.CellIndex(row = 41, column = 9)
    val JacName = ReportsViewModel.CellIndex(row = 40, column = 8)
    val JacValue = ReportsViewModel.CellIndex(row = 41, column = 8)
    val MgName = ReportsViewModel.CellIndex(row = 40, column = 7)
    val MgValue = ReportsViewModel.CellIndex(row = 41, column = 7)
}

object Branches {
    val ALMNTAKA_ALHORA_NAME = ReportsViewModel.CellIndex(row = 0, column = 3)
    val ALMNTAKA_ALHORA_SALES = ReportsViewModel.CellIndex(row = 9, column = 2)
    val KHALDA_MULTI_BRAND_NAME = ReportsViewModel.CellIndex(row = 10, column = 3)
    val KHALDA_MULTI_BRAND_SALES = ReportsViewModel.CellIndex(row = 17, column = 2)
    val KHALDA_DONGFENG_NAME = ReportsViewModel.CellIndex(row = 18, column = 3)
    val KHALDA_DONGFENG_SALES = ReportsViewModel.CellIndex(row = 26, column = 2)
    val ARBED_NAME = ReportsViewModel.CellIndex(row = 28, column = 3)
    val ARBED_SALES = ReportsViewModel.CellIndex(row = 36, column = 2)
    val FLEET_NAME = ReportsViewModel.CellIndex(row = 37, column = 3)
    val FLEET_SALES = ReportsViewModel.CellIndex(row = 39, column = 2)
}